# Generated by Django 4.0.6 on 2022-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('weather', models.CharField(max_length=200)),
                ('crop', models.CharField(max_length=200)),
            ],
        ),
    ]
